### ISSUE TITLE
Error generating email: Error: Error: Error getting cookies

### ISSUE THREAD

**Issue by kknd4eva** [jasp402/Easy-YOPmail#24]
Anyone had this issue before trying to generate mail addresses? 

`Error generating email: Error: Error: Error getting cookies
 - Error getting cookies
    at EasyYopmail.handleError (C:\Users\JMatson\source\repos\yopmail\node_modules\easy-yopmail\src\core.js:1:7631)
    at EasyYopmail.getMail (C:\Users\JMatson\source\repos\yopmail\node_modules\easy-yopmail\index.js:1:461)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateEmail (C:\Users\JMatson\source\repos\yopmail\yopmail.js:7:18)
    at async generateAddresses (C:\Users\JMatson\source\repos\yopmail\yopmail.js:20:21)
PS C:\Users\JMatson\source\repos\yopmail> `

**Comment by RealByron** [comment]
I have the same error with readMessage, I think that yopmail changes its API

**Comment by jasp402** [comment]
Please share with us the code you are using so we can see if it is the same case as issue #25 or something different.

**Comment by jasp402** [comment]
There are no more comments about this error. I think you have not received this error anymore. I will close this ticket.
